export default [
  {
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        Audio: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        SVGElement: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        MouseEvent: 'readonly',
        TouchEvent: 'readonly',
        KeyboardEvent: 'readonly',
        WheelEvent: 'readonly',
        getComputedStyle: 'readonly',
        matchMedia: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        screen: 'readonly',
        devicePixelRatio: 'readonly',
        Image: 'readonly',
        Path2D: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        WebGLRenderingContext: 'readonly',
        performance: 'readonly',
        structuredClone: 'readonly',
        crypto: 'readonly',
        AbortController: 'readonly',
      },
    },
    rules: {
      'no-undef': 'warn',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-redeclare': 'warn',
      'no-cond-assign': 'error',
      'no-constant-condition': 'warn',
      'no-dupe-keys': 'error',
      'no-empty': 'warn',
      'no-unreachable': 'error',
      'no-use-before-define': 'off',
      'no-irregular-whitespace': 'warn',
      'no-prototype-builtins': 'off',
      'no-fallthrough': 'warn',
      'no-self-assign': 'error',
      'no-shadow-restricted-names': 'error',
      'no-extra-semi': 'warn',
      'no-debugger': 'warn',
      'no-implicit-globals': 'warn',
      'valid-typeof': 'warn',
      'eqeqeq': 'off',
      'curly': 'off',
      'no-var': 'off',
      'prefer-const': 'off',
    },
    ignores: ['node_modules/', 'scripts/', 'test/', 'promo/'],
  },
  {
    files: ['js/**/*.js'],
    languageOptions: {
      globals: {
        State: 'readonly',
        Engine: 'readonly',
        UI: 'readonly',
        Sfx: 'readonly',
        Fx: 'readonly',
        Env: 'readonly',
        Art: 'readonly',
        Cutscene: 'readonly',
        Stage: 'readonly',
        ExploreMap: 'readonly',
        Chapters: 'readonly',
        STORY: 'readonly',
        WORLD: 'readonly',
        DATA: 'readonly',
        Balance: 'readonly',
        Settings: 'readonly',
        Main: 'readonly',
        BGM: 'readonly',
        weightedPick: 'readonly',
        clamp: 'readonly',
        rnd: 'readonly',
        choice: 'readonly',
      },
    },
  },
];
